# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.1
_src_path: gh:algorandfoundation/algokit-puya-template
author_email: xpanvictor@gmail.com
author_name: xpanvictor
contract_name: bitsave
deployment_language: python
preset_name: production
project_name: bs_rv_a

